/** Re-exporta la API MAP; mantiene compatibilidad con imports legacy. */
export {
  MAP_ROUTE_START,
  MUAAP_ROUTE_START,
  buildMapRoute,
  buildMuaapRoute,
  findNearestRoutePoint,
  haversineDistanceKm,
  quadrantPedestrianOrder,
  nearestNeighborOrder,
  reorderRouteFromPoint,
  parseMapCsvFile,
  parseMuaapCsvFile,
  type MapPointKind,
  type MapRoutePoint,
  type MapRouteResult,
  type MuaapPointKind,
  type MuaapRoutePoint,
  type MuaapRouteResult,
} from "@/lib/mapRoute";
