export type SocioProfileFormInitial = {
  businessName: string;
  website: string;
  googleBusinessUrl: string;
  category: string;
  address: string;
  street: string;
  streetNumber: string;
  colonia: string;
  codigoPostal: string;
  municipio: string;
  estado: string;
  pais: string;
  phone: string;
  latitude: number | null;
  longitude: number | null;
  contactFirstName: string;
  contactLastNamePaternal: string;
  contactLastNameMaternal: string;
  contactRole: string;
  contactBirthDate: string;
  contactWhatsapp: string;
  contactEmail: string;
  rfc: string;
  razonSocial: string;
  personaTipo: string;
  regimenFiscal: string;
  usoCfdi: string;
  billingStreet: string;
  billingStreetNumber: string;
  billingColonia: string;
  billingCiudad: string;
  billingMunicipio: string;
  billingEstado: string;
  billingPais: string;
  billingCodigoPostal: string;
  billingAddressFull: string;
  billingWhatsapp: string;
  billingEmail: string;
  billingSameWhatsapp: boolean;
  billingSameEmail: boolean;
  billingSameAddress: boolean;
  privacyAccepted: boolean;
};
